### ISSUE TITLE
iOS Background App Refresh

### ISSUE THREAD

**Issue by petebocken** [Ranchero-Software/NetNewsWireHelp#12]
I see NNW is listed for Background App Refresh, but does the app actually support this? I tried enabling it, but since there are no options for how often it would check feeds in the background I assume it’s not actually working.

I use On My iPhone and will use iCloud syncing when it’s available. In Brent’s latest inessential.com post, he brought up the issue of fast moving feeds and articles dropping off and missing them if you don’t open the app often. Seems like a background refresh would solve this issue.

**Comment by vincode-io** [comment]
The app does do background refreshes. We attempt to do them every 15 minutes, but iOS will determine when it actually gets scheduled based on your NNW usage patterns.

BTW, this is the repo for the Help Book. You should file future issues under the NetNewsWire repository.
