### ISSUE TITLE
I would like to change the font size on iOS

### ISSUE THREAD

**Issue by jukremer** [Ranchero-Software/NetNewsWireHelp#15]
I know I can change the font size for every app, but I would like to change it only for NNW.

**Comment by janurskremer** [comment]
Thank you for the recommendation! Unfortunately this changes the text size everywhere, not just in the article view. It would be awesome to change the text size only there with a slider. I suppose I could just make my own theme with a bigger font.

**Comment by vardecab** [comment]
If it's just for the article view you can create your own theme / customize an existing one. 

You can configure a theme to have both a larger font size and a better layout—reorder items, adjust line height, margins, text alignment, and more. Give it a try!
