### ISSUE TITLE
iPad app not syncing with iCloud

### ISSUE THREAD

**Issue by Lake161** [Ranchero-Software/NetNewsWireHelp#20]
Just started this morning, the iPad app hangs when syncing to iCloud. Tried delete/reinstall app with no success. The iPhone app is syncing just fine to the same iCloud account.

**Comment by brentsimmons** [comment]
What if you let it run for like an hour?

**Comment by Lake161** [comment]
Trying that now. Will let you know.

**Comment by Lake161** [comment]
No change. The bar at the bottom stays gray with no progress.

**Comment by Lake161** [comment]
It started working again this morning. I’d been checking it each day, and this time it worked. No idea what changed. Thanks for following up with me.

**Comment by vincode-io** [comment]
Looks like we are good here now.
