### ISSUE TITLE
Twitter list feed and Feedbin

### ISSUE THREAD

**Issue by felibb** [Ranchero-Software/NetNewsWireHelp#24]
I tried adding a Twitter list feed to Feedbin.com (I have a subscription) in NNW, but it failed, saying no feed found. Same list added perfectly fine to "On My Mac". Probably expected, since when I added the list via feedbin's web UI, it asked me to authorise the app first, added the list, and then it synced to NNW apps. Maybe this is something you could include to your guide as a side note for the future.

**Comment by vincode-io** [comment]
Because Twitter is removing Twitter API support very soon we will be completely be removing support for the Twitter Extension. That should end any confusion.
