### ISSUE TITLE
How To Turn Off the Unread Count in the Dock

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWireHelp#5]

**Comment by mariusb** [comment]
Just installed version 6.1 on a new Mac and it does not show the Unread count on the Dock icon.  
However on an old Mac where I also run version 6.1 but was upgraded from older versions the unread count is shown.

**Comment by brentsimmons** [comment]
Open System Preferences. Click on Notifications & Focus. Select NetNewsWire in the list on the left. Check or uncheck the “Badge app icon” checkbook.
